In [1]:
import numpy as np
import pandas as pd
import os
import requests
import json
import dotenv

In [2]:
dotenv.load_dotenv()

True

In [3]:
congresskey = os.getenv('congresskey')

There are five pieces of information you need to navigate any API and its poor documentation
1. How you get the API key (or another credential) to get access to the data (check)
2. Root: the beginning of the URL for any endpoint contained within the API 
A URL: `root / endpoint ? parameters` like youtube share ID
3. Endpoint: the middle of the URL, specifies which data store on the API to access
4. Parameters: ways to control what exactly is returned when you access an endpoint. Two kinds of parameters:
* Query parameters (appear after the ?, but reqests formats this for you using the `params` argument)
* Path parameters -- supposed to be entered as part of the endpoint itself
5. How to supply your API key back to the API to prove that you are you

In [4]:
root = 'https://api.congress.gov/v3'  # no slash at end of root bc slash is typically part of endpoint

endpoint = '/member'

params = {'format': 'json', 'currentMember': 'true', 'api_key': congresskey}

In [5]:
r = requests.get(root + endpoint, params=params)
r

In [6]:
r.text

'{\n    "members": [\n        {\n            "bioguideId": "W000832",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg"\n            },\n            "district": 14,\n            "name": "Wahab, Aisha",\n            "partyName": "Democratic",\n            "state": "California",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/W000832?format=json"\n        },\n        {\n            "bioguideId": "B001328",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg"\n            },\n            "district": 13,\n            "name": "Blair, Everton",\n            "partyName": "Democratic",\n            "state": "Georgia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/B001328?format=json"\n        },\n        {\n            "bioguideId": "G000607",\n            "depiction": {\n                "imageUrl": "https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg"\n            },\n            "district": 1,\n            "name": "Gallagher, James",\n            "partyName": "Republican",\n            "state": "California",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/G000607?format=json"\n        },\n        {\n            "bioguideId": "M001246",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg"\n            },\n            "district": 11,\n            "name": "Mejia, Analilia",\n            "partyName": "Democratic",\n            "state": "New Jersey",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/M001246?format=json"\n        },\n        {\n            "bioguideId": "F000485",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg"\n            },\n            "district": 14,\n            "name": "Fuller, Clay",\n            "partyName": "Republican",\n            "state": "Georgia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/F000485?format=json"\n        },\n        {\n            "bioguideId": "M001245",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg"\n            },\n            "district": 18,\n            "name": "Menefee, Christian D.",\n            "partyName": "Democratic",\n            "state": "Texas",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/M001245?format=json"\n        },\n        {\n            "bioguideId": "V000139",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg"\n            },\n            "district": 7,\n            "name": "Van Epps, Matt",\n            "partyName": "Republican",\n            "state": "Tennessee",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/V000139?format=json"\n        },\n        {\n            "bioguideId": "P000622",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg"\n            },\n            "district": 1,\n            "name": "Patronis, Jimmy",\n            "partyName": "Republican",\n            "state": "Florida",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/P000622?format=json"\n        },\n        {\n            "bioguideId": "F000484",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg"\n            },\n            "district": 6,\n            "name": "Fine, Randy",\n            "partyName": "Republican",\n            "state": "Florida",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/F000484?format=json"\n        },\n        {\n            "bioguideId": "V000138",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg"\n            },\n            "district": 7,\n            "name": "Vindman, Eugene Simon",\n            "partyName": "Democratic",\n            "state": "Virginia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/V000138?format=json"\n        },\n        {\n            "bioguideId": "T000490",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg"\n            },\n            "district": 2,\n            "name": "Taylor, David J.",\n            "partyName": "Republican",\n            "state": "Ohio",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/T000490?format=json"\n        },\n        {\n            "bioguideId": "S001230",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg"\n            },\n            "district": 10,\n            "name": "Subramanyam, Suhas",\n            "partyName": "Democratic",\n            "state": "Virginia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/S001230?format=json"\n        },\n        {\n            "bioguideId": "S001229",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg"\n            },\n            "district": 6,\n            "name": "Shreve, Jefferson",\n            "partyName": "Republican",\n            "state": "Indiana",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/S001229?format=json"\n        },\n        {\n            "bioguideId": "S001228",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg"\n            },\n            "district": 2,\n            "name": "Schmidt, Derek",\n            "partyName": "Republican",\n            "state": "Kansas",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/S001228?format=json"\n        },\n        {\n            "bioguideId": "R000622",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg"\n            },\n            "district": 19,\n            "name": "Riley, Josh",\n            "partyName": "Democratic",\n            "state": "New York",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/R000622?format=json"\n        },\n        {\n            "bioguideId": "P000621",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg"\n            },\n            "district": 9,\n            "name": "Pou, Nellie",\n            "partyName": "Democratic",\n            "state": "New Jersey",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/P000621?format=json"\n        },\n        {\n            "bioguideId": "O000176",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg"\n            },\n            "district": 2,\n            "name": "Olszewski, Johnny",\n            "partyName": "Democratic",\n            "state": "Maryland",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/O000176?format=json"\n        },\n        {\n            "bioguideId": "M001240",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg"\n            },\n            "district": 6,\n            "name": "McDowell, Addison P.",\n            "partyName": "Republican",\n            "state": "North Carolina",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/M001240?format=json"\n        },\n        {\n            "bioguideId": "M001239",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg"\n            },\n            "district": 5,\n            "name": "McGuire, John J.",\n            "partyName": "Republican",\n            "state": "Virginia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/M001239?format=json"\n        },\n        {\n            "bioguideId": "M001237",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/69d7f4ee7304cef7a0c977a8_200.jpg"\n            },\n            "district": 8,\n            "name": "McDonald Rivet, Kristen",\n            "partyName": "Democratic",\n            "state": "Michigan",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-10-23T07:40:24Z",\n            "url": "https://api.congress.gov/v3/member/M001237?format=json"\n        }\n    ],\n    "pagination": {\n        "count": 539,\n        "next": "https://api.congress.gov/v3/member?currentMember=true&offset=20&limit=20&format=json"\n    },\n    "request": {\n        "contentType": "application/json",\n        "format": "json"\n    }\n}'

In [7]:
r.json()

{'members': [{'bioguideId': 'W000832',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
   'district': 14,
   'name': 'Wahab, Aisha',
   'partyName': 'Democratic',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
  {'bioguideId': 'B001328',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
   'district': 13,
   'name': 'Blair, Everton',
   'partyName': 'Democratic',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
  {'bioguideId': 'G000607',
   'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
   'district': 1,
   'name': 'Gallagher, James',
   'partyName': 'Republican',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
  {'bioguideId': 'M001246',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
   'district': 11,
   'name': 'Mejia, Analilia',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
  {'bioguideId': 'F000485',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
   'district': 14,
   'name': 'Fuller, Clay',
   'partyName': 'Republican',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
  {'bioguideId': 'M001245',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
   'district': 18,
   'name': 'Menefee, Christian D.',
   'partyName': 'Democratic',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
  {'bioguideId': 'V000139',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
   'district': 7,
   'name': 'Van Epps, Matt',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
  {'bioguideId': 'P000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
   'district': 1,
   'name': 'Patronis, Jimmy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
  {'bioguideId': 'F000484',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
   'district': 6,
   'name': 'Fine, Randy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
  {'bioguideId': 'V000138',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
   'district': 7,
   'name': 'Vindman, Eugene Simon',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
  {'bioguideId': 'T000490',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
   'district': 2,
   'name': 'Taylor, David J.',
   'partyName': 'Republican',
   'state': 'Ohio',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
  {'bioguideId': 'S001230',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
   'district': 10,
   'name': 'Subramanyam, Suhas',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
  {'bioguideId': 'S001229',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
   'district': 6,
   'name': 'Shreve, Jefferson',
   'partyName': 'Republican',
   'state': 'Indiana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
  {'bioguideId': 'S001228',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
   'district': 2,
   'name': 'Schmidt, Derek',
   'partyName': 'Republican',
   'state': 'Kansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
  {'bioguideId': 'R000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
   'district': 19,
   'name': 'Riley, Josh',
   'partyName': 'Democratic',
   'state': 'New York',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
  {'bioguideId': 'P000621',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
   'district': 9,
   'name': 'Pou, Nellie',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
  {'bioguideId': 'O000176',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
   'district': 2,
   'name': 'Olszewski, Johnny',
   'partyName': 'Democratic',
   'state': 'Maryland',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
  {'bioguideId': 'M001240',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
   'district': 6,
   'name': 'McDowell, Addison P.',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001240?format=json'},
  {'bioguideId': 'M001239',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
   'district': 5,
   'name': 'McGuire, John J.',
   'partyName': 'Republican',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001239?format=json'},
  {'bioguideId': 'M001237',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69d7f4ee7304cef7a0c977a8_200.jpg'},
   'district': 8,
   'name': 'McDonald Rivet, Kristen',
   'partyName': 'Democratic',
   'state': 'Michigan',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001237?format=json'}],
 'pagination': {'count': 539,
  'next': 'https://api.congress.gov/v3/member?currentMember=true&offset=20&limit=20&format=json'},
 'request': {'contentType': 'application/json', 'format': 'json'}}

1. User-Agent strings/headers

A piece of text you give to the data server to tell them a bit about who you are and what your system is

2. Navigate a JSON

3. Pagination and rate limits

In [8]:
botname = 'ds6600'
version = '0.0'
purpose = 'Class demonstration'
email = 'gsu4aq@virginia.edu'
useragent = f'{botname}/{version} ({purpose}; {email}) python-requests/{requests.__version__}'
headers = {'User-Agent': useragent}
headers  # useragent

{'User-Agent': 'ds6600/0.0 (Class demonstration; gsu4aq@virginia.edu) python-requests/2.34.2'}

In [9]:
root = 'https://api.congress.gov/v3'
endpoint = '/member'
params = {'format': 'json',
          'currentMember': True,
          'api_key': congresskey}

r = requests.get(root + endpoint, params=params, headers=headers)  # the equals makes sure everything goes to the right place
r

In [10]:
myjson = r.json()
myjson

{'members': [{'bioguideId': 'W000832',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
   'district': 14,
   'name': 'Wahab, Aisha',
   'partyName': 'Democratic',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
  {'bioguideId': 'B001328',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
   'district': 13,
   'name': 'Blair, Everton',
   'partyName': 'Democratic',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
  {'bioguideId': 'G000607',
   'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
   'district': 1,
   'name': 'Gallagher, James',
   'partyName': 'Republican',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
  {'bioguideId': 'M001246',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
   'district': 11,
   'name': 'Mejia, Analilia',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
  {'bioguideId': 'F000485',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
   'district': 14,
   'name': 'Fuller, Clay',
   'partyName': 'Republican',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
  {'bioguideId': 'M001245',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
   'district': 18,
   'name': 'Menefee, Christian D.',
   'partyName': 'Democratic',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
  {'bioguideId': 'V000139',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
   'district': 7,
   'name': 'Van Epps, Matt',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
  {'bioguideId': 'P000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
   'district': 1,
   'name': 'Patronis, Jimmy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
  {'bioguideId': 'F000484',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
   'district': 6,
   'name': 'Fine, Randy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
  {'bioguideId': 'V000138',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
   'district': 7,
   'name': 'Vindman, Eugene Simon',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
  {'bioguideId': 'T000490',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
   'district': 2,
   'name': 'Taylor, David J.',
   'partyName': 'Republican',
   'state': 'Ohio',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
  {'bioguideId': 'S001230',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
   'district': 10,
   'name': 'Subramanyam, Suhas',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
  {'bioguideId': 'S001229',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
   'district': 6,
   'name': 'Shreve, Jefferson',
   'partyName': 'Republican',
   'state': 'Indiana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
  {'bioguideId': 'S001228',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
   'district': 2,
   'name': 'Schmidt, Derek',
   'partyName': 'Republican',
   'state': 'Kansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
  {'bioguideId': 'R000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
   'district': 19,
   'name': 'Riley, Josh',
   'partyName': 'Democratic',
   'state': 'New York',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
  {'bioguideId': 'P000621',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
   'district': 9,
   'name': 'Pou, Nellie',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
  {'bioguideId': 'O000176',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
   'district': 2,
   'name': 'Olszewski, Johnny',
   'partyName': 'Democratic',
   'state': 'Maryland',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
  {'bioguideId': 'M001240',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
   'district': 6,
   'name': 'McDowell, Addison P.',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001240?format=json'},
  {'bioguideId': 'M001239',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
   'district': 5,
   'name': 'McGuire, John J.',
   'partyName': 'Republican',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001239?format=json'},
  {'bioguideId': 'M001237',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69d7f4ee7304cef7a0c977a8_200.jpg'},
   'district': 8,
   'name': 'McDonald Rivet, Kristen',
   'partyName': 'Democratic',
   'state': 'Michigan',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-10-23T07:40:24Z',
   'url': 'https://api.congress.gov/v3/member/M001237?format=json'}],
 'pagination': {'count': 539,
  'next': 'https://api.congress.gov/v3/member?currentMember=True&offset=20&limit=20&format=json'},
 'request': {'contentType': 'application/json', 'format': 'json'}}

In [11]:
myjson.keys()

dict_keys(['members', 'pagination', 'request'])

In [12]:
myjson['members']

[{'bioguideId': 'W000832',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
  'district': 14,
  'name': 'Wahab, Aisha',
  'partyName': 'Democratic',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
 {'bioguideId': 'B001328',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
  'district': 13,
  'name': 'Blair, Everton',
  'partyName': 'Democratic',
  'state': 'Georgia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
 {'bioguideId': 'G000607',
  'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
  'district': 1,
  'name': 'Gallagher, James',
  'partyName': 'Republican',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
 {'bioguideId': 'M001246',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
  'district': 11,
  'name': 'Mejia, Analilia',
  'partyName': 'Democratic',
  'state': 'New Jersey',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
 {'bioguideId': 'F000485',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
  'district': 14,
  'name': 'Fuller, Clay',
  'partyName': 'Republican',
  'state': 'Georgia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
 {'bioguideId': 'M001245',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
  'district': 18,
  'name': 'Menefee, Christian D.',
  'partyName': 'Democratic',
  'state': 'Texas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
 {'bioguideId': 'V000139',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
  'district': 7,
  'name': 'Van Epps, Matt',
  'partyName': 'Republican',
  'state': 'Tennessee',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
 {'bioguideId': 'P000622',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
  'district': 1,
  'name': 'Patronis, Jimmy',
  'partyName': 'Republican',
  'state': 'Florida',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
 {'bioguideId': 'F000484',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
  'district': 6,
  'name': 'Fine, Randy',
  'partyName': 'Republican',
  'state': 'Florida',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
 {'bioguideId': 'V000138',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
  'district': 7,
  'name': 'Vindman, Eugene Simon',
  'partyName': 'Democratic',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
 {'bioguideId': 'T000490',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
  'district': 2,
  'name': 'Taylor, David J.',
  'partyName': 'Republican',
  'state': 'Ohio',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
 {'bioguideId': 'S001230',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
  'district': 10,
  'name': 'Subramanyam, Suhas',
  'partyName': 'Democratic',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
 {'bioguideId': 'S001229',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
  'district': 6,
  'name': 'Shreve, Jefferson',
  'partyName': 'Republican',
  'state': 'Indiana',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
 {'bioguideId': 'S001228',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
  'district': 2,
  'name': 'Schmidt, Derek',
  'partyName': 'Republican',
  'state': 'Kansas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
 {'bioguideId': 'R000622',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
  'district': 19,
  'name': 'Riley, Josh',
  'partyName': 'Democratic',
  'state': 'New York',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
 {'bioguideId': 'P000621',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
  'district': 9,
  'name': 'Pou, Nellie',
  'partyName': 'Democratic',
  'state': 'New Jersey',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
 {'bioguideId': 'O000176',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
  'district': 2,
  'name': 'Olszewski, Johnny',
  'partyName': 'Democratic',
  'state': 'Maryland',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
 {'bioguideId': 'M001240',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
  'district': 6,
  'name': 'McDowell, Addison P.',
  'partyName': 'Republican',
  'state': 'North Carolina',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/M001240?format=json'},
 {'bioguideId': 'M001239',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
  'district': 5,
  'name': 'McGuire, John J.',
  'partyName': 'Republican',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/M001239?format=json'},
 {'bioguideId': 'M001237',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/69d7f4ee7304cef7a0c977a8_200.jpg'},
  'district': 8,
  'name': 'McDonald Rivet, Kristen',
  'partyName': 'Democratic',
  'state': 'Michigan',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-10-23T07:40:24Z',
  'url': 'https://api.congress.gov/v3/member/M001237?format=json'}]

In [13]:
len(myjson['members'])

20

In [14]:
myjson['members'][0]['terms']['item'][0]['chamber']

'House of Representatives'

Record path -- somewhere in the JSON is a list where each item is one row of the dataframe you want to build. The record path is the sequence of keys to call to arrive at this list.

In this case the record path is: just members

In [15]:
congress_df = pd.json_normalize(myjson, record_path=['members'])
congress_df

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14,"Wahab, Aisha",Democratic,California,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13,"Blair, Everton",Democratic,Georgia,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1,"Gallagher, James",Republican,California,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11,"Mejia, Analilia",Democratic,New Jersey,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14,"Fuller, Clay",Republican,Georgia,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
5,M001245,18,"Menefee, Christian D.",Democratic,Texas,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/M001245?for...,Image courtesy of the Member,https://www.congress.gov/img/member/698206b2eb...,"[{'chamber': 'House of Representatives', 'star..."
6,V000139,7,"Van Epps, Matt",Republican,Tennessee,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/V000139?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6931b7d5f4...,"[{'chamber': 'House of Representatives', 'star..."
7,P000622,1,"Patronis, Jimmy",Republican,Florida,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/P000622?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67efdb991b...,"[{'chamber': 'House of Representatives', 'star..."
8,F000484,6,"Fine, Randy",Republican,Florida,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/F000484?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67efda8c1b...,"[{'chamber': 'House of Representatives', 'star..."
9,V000138,7,"Vindman, Eugene Simon",Democratic,Virginia,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/V000138?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6774617a0b...,"[{'chamber': 'House of Representatives', 'star..."
10,T000490,2,"Taylor, David J.",Republican,Ohio,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/T000490?for...,Image courtesy of the Member,https://www.congress.gov/img/member/677460190b...,"[{'chamber': 'House of Representatives', 'star..."
11,S001230,10,"Subramanyam, Suhas",Democratic,Virginia,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/S001230?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6797be8bc7...,"[{'chamber': 'House of Representatives', 'star..."
12,S001229,6,"Shreve, Jefferson",Republican,Indiana,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/S001229?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745f0e0b...,"[{'chamber': 'House of Representatives', 'star..."
13,S001228,2,"Schmidt, Derek",Republican,Kansas,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/S001228?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745ec50b...,"[{'chamber': 'House of Representatives', 'star..."
14,R000622,19,"Riley, Josh",Democratic,New York,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/R000622?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745e360b...,"[{'chamber': 'House of Representatives', 'star..."
15,P000621,9,"Pou, Nellie",Democratic,New Jersey,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/P000621?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745d3b0b...,"[{'chamber': 'House of Representatives', 'star..."
16,O000176,2,"Olszewski, Johnny",Democratic,Maryland,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/O000176?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a3974507d...,"[{'chamber': 'House of Representatives', 'star..."
17,M001240,6,"McDowell, Addison P.",Republican,North Carolina,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/M001240?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67744e930b...,"[{'chamber': 'House of Representatives', 'star..."
18,M001239,5,"McGuire, John J.",Republican,Virginia,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/M001239?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67744ba20b...,"[{'chamber': 'House of Representatives', 'star..."
19,M001237,8,"McDonald Rivet, Kristen",Democratic,Michigan,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/M001237?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69d7f4ee73...,"[{'chamber': 'House of Representatives', 'star..."

In [16]:
params['limit'] = '250'
# params DO NOT WRITE THIS IT WILL EXPOSE YOUR KEY !!

In [17]:
r = requests.get(root + endpoint, params=params, headers=headers)
myjson = r.json()
congress_df =  pd.json_normalize(myjson, record_path=['members'])
# pd.set_option(max rows) DO NOT WRITE THIS IT WILL CRASH YOUR COMPUTER IF U HAVE A LARGE AMNT OF ROWS !!
congress_df

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14.0,"Wahab, Aisha",Democratic,California,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13.0,"Blair, Everton",Democratic,Georgia,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1.0,"Gallagher, James",Republican,California,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11.0,"Mejia, Analilia",Democratic,New Jersey,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14.0,"Fuller, Clay",Republican,Georgia,2026-10-23T07:40:24Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
...,...,...,...,...,...,...,...,...,...,...
245,C001120,2.0,"Crenshaw, Dan",Republican,Texas,2026-10-23T07:40:20Z,https://api.congress.gov/v3/member/C001120?for...,Image courtesy of the Member,https://www.congress.gov/img/member/698a13d0a7...,"[{'chamber': 'House of Representatives', 'star..."
246,R000612,6.0,"Rose, John W.",Republican,Tennessee,2026-10-23T07:40:20Z,https://api.congress.gov/v3/member/R000612?for...,Image courtesy of the Member,https://www.congress.gov/img/member/r000612_20...,"[{'chamber': 'House of Representatives', 'star..."
247,B001309,2.0,"Burchett, Tim",Republican,Tennessee,2026-10-23T07:40:20Z,https://api.congress.gov/v3/member/B001309?for...,Image courtesy of the Member,https://www.congress.gov/img/member/b001309_20...,"[{'chamber': 'House of Representatives', 'star..."
248,J000301,NaN,"Johnson, Dusty",Republican,South Dakota,2026-10-23T07:40:20Z,https://api.congress.gov/v3/member/J000301?for...,Image courtesy of the Member,https://www.congress.gov/img/member/j000301_20...,"[{'chamber': 'House of Representatives', 'star..."
249,T000480,4.0,"Timmons, William R.",Republican,South Carolina,2026-10-23T07:40:20Z,https://api.congress.gov/v3/member/T000480?for...,Image courtesy of the Member,https://www.congress.gov/img/member/t000480_20...,"[{'chamber': 'House of Representatives', 'star..."

In [18]:
params['offset'] = '500'
r = requests.get(root + endpoint, params=params, headers=headers)
myjson = r.json()
myjson
# congress_df =  pd.json_normalize(myjson, record_path=['members'])
# congress_df

{'members': [{'bioguideId': 'H001104',
   'depiction': {'attribution': 'Official U.S. Senate Photo',
    'imageUrl': 'https://www.congress.gov/img/member/67f0316b1b05a5a598f7fdf3_200.jpg'},
   'name': 'Husted, Jon',
   'partyName': 'Republican',
   'state': 'Ohio',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2025}]},
   'updateDate': '2026-03-08T10:31:32Z',
   'url': 'https://api.congress.gov/v3/member/H001104?format=json'},
  {'bioguideId': 'H001061',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/h001061_200.jpg'},
   'name': 'Hoeven, John',
   'partyName': 'Republican',
   'state': 'North Dakota',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2011}]},
   'updateDate': '2026-03-08T10:31:30Z',
   'url': 'https://api.congress.gov/v3/member/H001061?format=json'},
  {'bioguideId': 'H001042',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/h001042_200.jpg'},
   'name': 'Hirono, Mazie K.',
   'partyName': 'Democratic',
   'state': 'Hawaii',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2013,
      'startYear': 2007},
     {'chamber': 'Senate', 'startYear': 2013}]},
   'updateDate': '2026-03-08T10:31:28Z',
   'url': 'https://api.congress.gov/v3/member/H001042?format=json'},
  {'bioguideId': 'H000273',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/h000273_200.jpg'},
   'name': 'Hickenlooper, John W.',
   'partyName': 'Democratic',
   'state': 'Colorado',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2021}]},
   'updateDate': '2026-03-08T10:31:27Z',
   'url': 'https://api.congress.gov/v3/member/H000273?format=json'},
  {'bioguideId': 'H001046',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/h001046_200.jpg'},
   'name': 'Heinrich, Martin',
   'partyName': 'Democratic',
   'state': 'New Mexico',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2013,
      'startYear': 2009},
     {'chamber': 'Senate', 'startYear': 2013}]},
   'updateDate': '2026-03-08T10:31:25Z',
   'url': 'https://api.congress.gov/v3/member/H001046?format=json'},
  {'bioguideId': 'H001089',
   'depiction': {'imageUrl': 'https://www.congress.gov/img/member/h001089_200.jpg'},
   'name': 'Hawley, Josh',
   'partyName': 'Republican',
   'state': 'Missouri',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2019}]},
   'updateDate': '2026-03-08T10:31:24Z',
   'url': 'https://api.congress.gov/v3/member/H001089?format=json'},
  {'bioguideId': 'H001076',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/h001076_200.jpg'},
   'name': 'Hassan, Margaret Wood',
   'partyName': 'Democratic',
   'state': 'New Hampshire',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2017}]},
   'updateDate': '2026-03-08T10:31:22Z',
   'url': 'https://api.congress.gov/v3/member/H001076?format=json'},
  {'bioguideId': 'H000601',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/h000601_200.jpg'},
   'name': 'Hagerty, Bill',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2021}]},
   'updateDate': '2026-03-08T10:31:20Z',
   'url': 'https://api.congress.gov/v3/member/H000601?format=json'},
  {'bioguideId': 'G000555',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/g000555_200.jpg'},
   'name': 'Gillibrand, Kirsten E.',
   'partyName': 'Democratic',
   'state': 'New York',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2009,
      'startYear': 2007},
     {'chamber': 'Senate', 'startYear': 2009}]},
   'updateDate': '2026-03-08T10:31:15Z',
   'url': 'https://api.congress.gov/v3/member/G000555?format=json'},
  {'bioguideId': 'G000574',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/c6870f487cf4bc9a568d8afbe61d754b_200.jpg'},
   'name': 'Gallego, Ruben',
   'partyName': 'Democratic',
   'state': 'Arizona',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2025,
      'startYear': 2015},
     {'chamber': 'Senate', 'startYear': 2025}]},
   'updateDate': '2026-03-08T10:31:14Z',
   'url': 'https://api.congress.gov/v3/member/G000574?format=json'},
  {'bioguideId': 'F000463',
   'depiction': {'attribution': 'Official U.S. Senate Photo',
    'imageUrl': 'https://www.congress.gov/img/member/669ec7925d19788d1f2034a1_200.jpg'},
   'name': 'Fischer, Deb',
   'partyName': 'Republican',
   'state': 'Nebraska',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2013}]},
   'updateDate': '2026-03-08T10:31:12Z',
   'url': 'https://api.congress.gov/v3/member/F000463?format=json'},
  {'bioguideId': 'F000479',
   'depiction': {'attribution': 'Official U.S. Senate Photo',
    'imageUrl': 'https://www.congress.gov/img/member/f000479_200.jpg'},
   'name': 'Fetterman, John',
   'partyName': 'Democratic',
   'state': 'Pennsylvania',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2023}]},
   'updateDate': '2026-03-08T10:31:11Z',
   'url': 'https://api.congress.gov/v3/member/F000479?format=json'},
  {'bioguideId': 'E000295',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/e000295_200.jpg'},
   'name': 'Ernst, Joni',
   'partyName': 'Republican',
   'state': 'Iowa',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2015}]},
   'updateDate': '2026-03-08T10:31:09Z',
   'url': 'https://api.congress.gov/v3/member/E000295?format=json'},
  {'bioguideId': 'D000563',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/d000563_200.jpg'},
   'name': 'Durbin, Richard J.',
   'partyName': 'Democratic',
   'state': 'Illinois',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 1997,
      'startYear': 1983},
     {'chamber': 'Senate', 'startYear': 1997}]},
   'updateDate': '2026-03-08T10:31:07Z',
   'url': 'https://api.congress.gov/v3/member/D000563?format=json'},
  {'bioguideId': 'D000622',
   'depiction': {'attribution': 'Courtesy U.S. Senate Historical Office',
    'imageUrl': 'https://www.congress.gov/img/member/d000622_200.jpg'},
   'name': 'Duckworth, Tammy',
   'partyName': 'Democratic',
   'state': 'Illinois',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2017,
      'startYear': 2013},
     {'chamber': 'Senate', 'startYear': 2017}]},
   'updateDate': '2026-03-08T10:31:06Z',
   'url': 'https://api.congress.gov/v3/member/D000622?format=json'},
  {'bioguideId': 'D000618',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/d000618_200.jpg'},
   'name': 'Daines, Steve',
   'partyName': 'Republican',
   'state': 'Montana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2015,
      'startYear': 2013},
     {'chamber': 'Senate', 'startYear': 2015}]},
   'updateDate': '2026-03-08T10:31:04Z',
   'url': 'https://api.congress.gov/v3/member/D000618?format=json'},
  {'bioguideId': 'C001114',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/1b9d1007d6895a37da28a67cd8149803_200.jpg'},
   'name': 'Curtis, John R.',
   'partyName': 'Republican',
   'state': 'Utah',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2025,
      'startYear': 2017},
     {'chamber': 'Senate', 'startYear': 2025}]},
   'updateDate': '2026-03-08T10:31:03Z',
   'url': 'https://api.congress.gov/v3/member/C001114?format=json'},
  {'bioguideId': 'C001098',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c001098_200.jpg'},
   'name': 'Cruz, Ted',
   'partyName': 'Republican',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2013}]},
   'updateDate': '2026-03-08T10:31:01Z',
   'url': 'https://api.congress.gov/v3/member/C001098?format=json'},
  {'bioguideId': 'C000880',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c000880_200.jpg'},
   'name': 'Crapo, Mike',
   'partyName': 'Republican',
   'state': 'Idaho',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 1999,
      'startYear': 1993},
     {'chamber': 'Senate', 'startYear': 1999}]},
   'updateDate': '2026-03-08T10:31:00Z',
   'url': 'https://api.congress.gov/v3/member/C000880?format=json'},
  {'bioguideId': 'C001096',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/c001096_200.jpg'},
   'name': 'Cramer, Kevin',
   'partyName': 'Republican',
   'state': 'North Dakota',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2019,
      'startYear': 2013},
     {'chamber': 'Senate', 'startYear': 2019}]},
   'updateDate': '2026-03-08T10:30:58Z',
   'url': 'https://api.congress.gov/v3/member/C001096?format=json'},
  {'bioguideId': 'C001095',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c001095_200.jpg'},
   'name': 'Cotton, Tom',
   'partyName': 'Republican',
   'state': 'Arkansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2015,
      'startYear': 2013},
     {'chamber': 'Senate', 'startYear': 2015}]},
   'updateDate': '2026-03-08T10:30:57Z',
   'url': 'https://api.congress.gov/v3/member/C001095?format=json'},
  {'bioguideId': 'C001113',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c001113_200.jpg'},
   'name': 'Cortez Masto, Catherine',
   'partyName': 'Democratic',
   'state': 'Nevada',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2017}]},
   'updateDate': '2026-03-08T10:30:55Z',
   'url': 'https://api.congress.gov/v3/member/C001113?format=json'},
  {'bioguideId': 'C001056',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c001056_200.jpg'},
   'name': 'Cornyn, John',
   'partyName': 'Republican',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2002}]},
   'updateDate': '2026-03-08T10:30:53Z',
   'url': 'https://api.congress.gov/v3/member/C001056?format=json'},
  {'bioguideId': 'C001088',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c001088_200.jpg'},
   'name': 'Coons, Christopher A.',
   'partyName': 'Democratic',
   'state': 'Delaware',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2010}]},
   'updateDate': '2026-03-08T10:30:51Z',
   'url': 'https://api.congress.gov/v3/member/C001088?format=json'},
  {'bioguideId': 'C001035',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c001035_200.jpg'},
   'name': 'Collins, Susan M.',
   'partyName': 'Republican',
   'state': 'Maine',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 1997}]},
   'updateDate': '2026-03-08T10:30:49Z',
   'url': 'https://api.congress.gov/v3/member/C001035?format=json'},
  {'bioguideId': 'C001075',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c001075_200.jpg'},
   'name': 'Cassidy, Bill',
   'partyName': 'Republican',
   'state': 'Louisiana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2015,
      'startYear': 2009},
     {'chamber': 'Senate', 'startYear': 2015}]},
   'updateDate': '2026-03-08T10:30:47Z',
   'url': 'https://api.congress.gov/v3/member/C001075?format=json'},
  {'bioguideId': 'C001047',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c001047_200.jpg'},
   'name': 'Capito, Shelley Moore',
   'partyName': 'Republican',
   'state': 'West Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2015,
      'startYear': 2001},
     {'chamber': 'Senate', 'startYear': 2015}]},
   'updateDate': '2026-03-08T10:30:45Z',
   'url': 'https://api.congress.gov/v3/member/C001047?format=json'},
  {'bioguideId': 'C000127',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/c000127_200.jpg'},
   'name': 'Cantwell, Maria',
   'partyName': 'Democratic',
   'state': 'Washington',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 1995,
      'startYear': 1993},
     {'chamber': 'Senate', 'startYear': 2001}]},
   'updateDate': '2026-03-08T10:30:43Z',
   'url': 'https://api.congress.gov/v3/member/C000127?format=json'},
  {'bioguideId': 'B001305',
   'depiction': {'attribution': 'Official U.S. Senate Photo',
    'imageUrl': 'https://www.congress.gov/img/member/b001305_200.jpg'},
   'name': 'Budd, Ted',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2023,
      'startYear': 2017},
     {'chamber': 'Senate', 'startYear': 2023}]},
   'updateDate': '2026-03-08T10:30:42Z',
   'url': 'https://api.congress.gov/v3/member/B001305?format=json'},
  {'bioguideId': 'B001319',
   'depiction': {'attribution': '<p>Official U.S. Senate Photo</p>',
    'imageUrl': 'https://www.congress.gov/img/member/b001319_200.jpg'},
   'name': 'Britt, Katie Boyd',
   'partyName': 'Republican',
   'state': 'Alabama',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2023}]},
   'updateDate': '2026-03-08T10:30:40Z',
   'url': 'https://api.congress.gov/v3/member/B001319?format=json'},
  {'bioguideId': 'B001236',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/b001236_200.jpg'},
   'name': 'Boozman, John',
   'partyName': 'Republican',
   'state': 'Arkansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2011,
      'startYear': 2001},
     {'chamber': 'Senate', 'startYear': 2011}]},
   'updateDate': '2026-03-08T10:30:38Z',
   'url': 'https://api.congress.gov/v3/member/B001236?format=json'},
  {'bioguideId': 'B001303',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/b001303_200.jpg'},
   'name': 'Blunt Rochester, Lisa',
   'partyName': 'Democratic',
   'state': 'Delaware',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2025,
      'startYear': 2017},
     {'chamber': 'Senate', 'startYear': 2025}]},
   'updateDate': '2026-03-08T10:30:34Z',
   'url': 'https://api.congress.gov/v3/member/B001303?format=json'},
  {'bioguideId': 'B001277',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/b001277_200.jpg'},
   'name': 'Blumenthal, Richard',
   'partyName': 'Democratic',
   'state': 'Connecticut',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2011}]},
   'updateDate': '2026-03-08T10:30:33Z',
   'url': 'https://api.congress.gov/v3/member/B001277?format=json'},
  {'bioguideId': 'B001243',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/b001243_200.jpg'},
   'name': 'Blackburn, Marsha',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'endYear': 2019,
      'startYear': 2003},
     {'chamber': 'Senate', 'startYear': 2019}]},
   'updateDate': '2026-03-08T10:30:31Z',
   'url': 'https://api.congress.gov/v3/member/B001243?format=json'},
  {'bioguideId': 'B001267',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',
    'imageUrl': 'https://www.congress.gov/img/member/b001267_200.jpg'},
   'name': 'Bennet, Michael F.',
   'partyName': 'Democratic',
   'state': 'Colorado',
   'terms': {'item': [{'chamber': 'Senate', 'startYear': 2009}]},
   'updateDate': '2026-03-08T10:30:30Z',
   'url': 'https://api.congress.gov/v3/member/B001267?format=json'},
  {'bioguideId': 'B001261',
   'depiction': {'attribution': '<a href="http://www.senate.gov/artandhistory/history/common/generic/Photo_Collection_of_the_Senate_Historical_Office.htm">Courtesy U.S. Senate Historical Office</a>',

In [19]:
i = 0
# still_members = True
congress_json = []
while i < total_count:  # > 0
    params['offset'] = i
    r = requests.get(root + endpoint, params=params, headers=headers)
    myjson = r.json()
    # still_members = len(myjson['members']) > 0
    total_count = myjson['pagination']['count']
    congress_json.extend(myjson['members'])
    i = i + 250

NameError: name 'total_count' is not defined

In [ ]:
len(congress_json)

In [ ]:
congress_df = pd.json_normalize(congress_json)
congress_df

In [ ]:
mcguire_df = congress_df.query("state == 'Virginia' & district == 5")

In [ ]:
bioguideId = mcguire_df.reset_index()['bioguideId'][0]  # why?

In [ ]:
endpoint = f'/member/{bioguideId}'  # member not memberS !!!!!
endpoint

In [ ]:
params = {'api_key': congresskey, 'format': 'json'}
r = requests.get(root + endpoint, params=params, headers=headers)
r

In [ ]:
r.json()

In [ ]:
bioguideId

In [ ]:
endpoint = f'/member/{bioguideId}/sponsored-legislation'

params = {'api_key': congresskey, 'format': 'json'}
r = requests.get(root + endpoint, params=params, headers=headers)
r

In [ ]:
mcguire_bills_df = pd.json_normalize(r.json(), record_path=['sponsoredLegislation'])
pd.set_option('display.max_rows', 20)
mcguire_bills_df['title']

In [ ]:
mcguire_bills_df.loc[11]  # why not iloc?